### PR TITLE
enhancement(log): refresh file status badge if file change occurs when gitout is deactivated

### PR DESCRIPTION
**Pull request by calahatras**

### CODE REVIEW

**Comment by mickedefault** [comment]
hm.. it triggers, even when running `git status` externally. 🤔 I guess some file in .git is modified which triggers a reload.
should we try to limit it to project files and new files?

**Comment by calahatras** [comment]
> hm.. it triggers, even when running `git status` externally. 🤔 I guess some file in .git is modified which triggers a reload.
> should we try to limit it to project files and new files?

Good question. We _could_ limit this to only checking for files outside the git folder (i.e. the actual project files), but then we would miss e.g. checking out new branches and stuff that could merit a refresh 🤔

**Comment by calahatras** [comment]
@mickedefault What about limiting the changes to project files only (i.e. ignore .git folder) and remove the snack, are you OK with that change?

**Comment by mickedefault** [comment]
actually I more than often need to refresh due to the git changing. It's less friction to reopen the commit than having to click the refresh button in the top corner.
I'd vote for skipping the latest commits changes regarding the .git folder.

**Review by mickedefault — DISMISSED** [review]

**Review by mickedefault — DISMISSED** [review]

**Review by mickedefault — APPROVED** [review]

**Pull request merged**
